# IllumiDesk configuration values
# --------------------
# Create and use roles and service accounts on an RBAC enabled cluster.
rbac:
    enabled: true

jupyterhub:
# Helm config for jupyterhub goes here
# See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml
    hub:
      image:
        name: illumidesk/k8s-hub
        tag: latest
      shutdownOnLogout: true
    proxy:
      https:
        enabled: false
      secretToken: ''
      service:
        # ports:
        #   nodePort: 8080
        type: ClusterIP
    singleuser:
      cmd: start-singleuser.sh
      extraEnv:
        CHOWN_HOME: 'yes'
        Editor: vim
      fsGid: 0
      uid: 0
      image:
        name: illumidesk/illumidesk-notebook
        tag: latest
      storage:
        capacity: 2Gi
        extraVolumes:
          - name: jupyterhub-shared
            persistentVolumeClaim:
              claimName: jhub-shared-volume
        extraVolumeMounts:
          - name: jupyterhub-shared
            mountPath: /srv/nbgrader
