apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-ingress 
  namespace: {{ .Release.nNmespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: {{ .Values.subnets }}
    alb.ingress.kubernetes.io/tags: {{ .Values.ingressTags }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: proxy-public
          servicePort: 80